name: SonarCloud analysis

on:
  push:
    branches:
      - main
      - branch-*   # Includes any branch starting with "branch-"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # Allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # GitHub Action secret for SonarCloud authentication
        with:
          args: |
            -Dsonar.projectKey=amankrs21_Security-Vault   # Replace with your SonarCloud project key
            -Dsonar.organization=amankrs21  # Replace with your SonarCloud organization key
            -Dsonar.verbose=true     # Optional: Enable verbose logging
          projectBaseDir: .
